SELECT
    LOCOMOTIVE.ID,
    LOCOMOTIVE.TRAINOPERATORNAME,
    LOCOMOTIVE.MODELNAME
FROM
    LOCOMOTIVE,
    LOCOMOTIVEMODEL,
    LOCOMOTIVEMODEL_GAUGE
WHERE
        LOCOMOTIVE.MODELNAME = LOCOMOTIVEMODEL.NAME
    AND LOCOMOTIVEMODEL.NAME = LOCOMOTIVEMODEL_GAUGE.LOCOMOTIVEMODELNAME
    AND LOCOMOTIVEMODEL_GAUGE.GAUGEWIDTH = 1668;